"""Initial

Revision ID: 98ca23793dee
Revises: 
Create Date: 2026-07-24 22:38:51.502708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98ca23793dee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.Enum('YOLO', 'FACE_RECOGNITION', 'POSE_ESTIMATION', 'CROWD_ANALYSIS', name='ai_model_type_enum'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('iou', sa.Float(), nullable=False),
    sa.Column('input_size', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_loaded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_id'), 'ai_models', ['id'], unique=False)
    op.create_index(op.f('ix_ai_models_is_active'), 'ai_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_models_model_type'), 'ai_models', ['model_type'], unique=False)
    op.create_index(op.f('ix_ai_models_name'), 'ai_models', ['name'], unique=False)
    op.create_table('camera_groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_groups_id'), 'camera_groups', ['id'], unique=False)
    op.create_index(op.f('ix_camera_groups_name'), 'camera_groups', ['name'], unique=True)
    op.create_table('criminal_watchlist',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('face_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('face_image_path', sa.String(length=500), nullable=True),
    sa.Column('threat_level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index(op.f('ix_criminal_watchlist_id'), 'criminal_watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_criminal_watchlist_name'), 'criminal_watchlist', ['name'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('service_statuses',
    sa.Column('service_name', sa.Enum('PERSON_DETECTION', 'QUEUE_ANALYSIS', 'ZONE_MONITORING', 'FACE_RECOGNITION', 'CAMERA_STREAM', 'ALERT_ENGINE', name='service_name_enum'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'STOPPED', 'ERROR', 'STARTING', 'STOPPING', name='service_status_val_enum'), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('gpu_usage', sa.Float(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_statuses_id'), 'service_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_service_statuses_service_name'), 'service_statuses', ['service_name'], unique=True)
    op.create_index(op.f('ix_service_statuses_status'), 'service_statuses', ['status'], unique=False)
    op.create_index(op.f('ix_service_statuses_updated_at'), 'service_statuses', ['updated_at'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_category'), 'system_settings', ['category'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='user_status_enum'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('zones',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('warning_threshold', sa.Integer(), nullable=False),
    sa.Column('critical_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_logged_at'), 'audit_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cameras',
    sa.Column('camera_name', sa.String(length=150), nullable=False),
    sa.Column('camera_type', sa.Enum('ENTRY', 'EXIT', 'ZONE', 'QUEUE', 'FACE', name='camera_type_enum'), nullable=False),
    sa.Column('rtsp_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'MAINTENANCE', 'ERROR', name='camera_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stream_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_connected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_frame_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['camera_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_camera_name'), 'cameras', ['camera_name'], unique=True)
    op.create_index(op.f('ix_cameras_camera_type'), 'cameras', ['camera_type'], unique=False)
    op.create_index(op.f('ix_cameras_group_id'), 'cameras', ['group_id'], unique=False)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_index(op.f('ix_cameras_is_active'), 'cameras', ['is_active'], unique=False)
    op.create_index(op.f('ix_cameras_status'), 'cameras', ['status'], unique=False)
    op.create_index(op.f('ix_cameras_zone_id'), 'cameras', ['zone_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('zone_counts',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_counts_id'), 'zone_counts', ['id'], unique=False)
    op.create_index(op.f('ix_zone_counts_recorded_at'), 'zone_counts', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_zone_counts_zone_id'), 'zone_counts', ['zone_id'], unique=False)
    op.create_table('camera_health',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('gpu_usage', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('decode_fps', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_health_camera_id'), 'camera_health', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_health_id'), 'camera_health', ['id'], unique=False)
    op.create_index(op.f('ix_camera_health_recorded_at'), 'camera_health', ['recorded_at'], unique=False)
    op.create_table('entry_exit_counts',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('exit_count', sa.Integer(), nullable=False),
    sa.Column('net_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_exit_counts_camera_id'), 'entry_exit_counts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_entry_exit_counts_id'), 'entry_exit_counts', ['id'], unique=False)
    op.create_index(op.f('ix_entry_exit_counts_recorded_at'), 'entry_exit_counts', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_entry_exit_counts_zone_id'), 'entry_exit_counts', ['zone_id'], unique=False)
    op.create_table('face_detection_logs',
    sa.Column('watchlist_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('face_image_path', sa.String(length=500), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['criminal_watchlist.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_detection_logs_camera_id'), 'face_detection_logs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_face_detection_logs_detected_at'), 'face_detection_logs', ['detected_at'], unique=False)
    op.create_index(op.f('ix_face_detection_logs_id'), 'face_detection_logs', ['id'], unique=False)
    op.create_index(op.f('ix_face_detection_logs_watchlist_id'), 'face_detection_logs', ['watchlist_id'], unique=False)
    op.create_index(op.f('ix_face_detection_logs_zone_id'), 'face_detection_logs', ['zone_id'], unique=False)
    op.create_table('queues',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queues_camera_id'), 'queues', ['camera_id'], unique=False)
    op.create_index(op.f('ix_queues_id'), 'queues', ['id'], unique=False)
    op.create_index(op.f('ix_queues_name'), 'queues', ['name'], unique=True)
    op.create_index(op.f('ix_queues_zone_id'), 'queues', ['zone_id'], unique=False)
    op.create_table('rois',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('roi_type', sa.Enum('COUNTING_LINE', 'POLYGON_ZONE', 'ENTRY_GATE', 'EXIT_GATE', 'RESTRICTED', name='roi_type_enum'), nullable=False),
    sa.Column('direction', sa.Enum('ENTRY', 'EXIT', 'BOTH', name='roi_direction_enum'), nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rois_camera_id'), 'rois', ['camera_id'], unique=False)
    op.create_index(op.f('ix_rois_id'), 'rois', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.Enum('CROWD_OVERFLOW', 'QUEUE_CRITICAL', 'CAMERA_OFFLINE', 'FACE_MATCH', 'ZONE_CAPACITY', 'SYSTEM_ERROR', name='alert_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status_enum'), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('queue_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=150), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=150), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_camera_id'), 'alerts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_queue_id'), 'alerts', ['queue_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_zone_id'), 'alerts', ['zone_id'], unique=False)
    op.create_table('queue_snapshots',
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('waiting_time', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('NORMAL', 'MODERATE', 'HEAVY', 'CRITICAL', name='queue_status_enum'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_snapshots_captured_at'), 'queue_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_queue_snapshots_id'), 'queue_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_queue_snapshots_queue_id'), 'queue_snapshots', ['queue_id'], unique=False)
    op.create_index(op.f('ix_queue_snapshots_status'), 'queue_snapshots', ['status'], unique=False)
    op.create_table('events',
    sa.Column('event_type', sa.Enum('QUEUE_ALERT', 'ZONE_ALERT', 'CAMERA_OFFLINE', 'CAMERA_ONLINE', 'FACE_MATCH', 'ENTRY_CLOSED', 'SYSTEM_START', 'SYSTEM_STOP', 'AI_MODEL_LOADED', 'AI_MODEL_ERROR', 'CROWD_SURGE', 'CAMERA_ERROR', name='event_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='event_severity_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('queue_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=150), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_alert_id'), 'events', ['alert_id'], unique=False)
    op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_queue_id'), 'events', ['queue_id'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_zone_id'), 'events', ['zone_id'], unique=False)
    op.create_table('notifications',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'WHATSAPP', 'DASHBOARD', name='notification_channel_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'DELIVERED', name='notification_status_enum'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_alert_id'), 'notifications', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('snapshots',
    sa.Column('snapshot_type', sa.Enum('FACE_DETECTION', 'ZONE_ALERT', 'CROWD_ALERT', 'CAMERA_HEALTH', name='snapshot_type_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('snapshot_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_alert_id'), 'snapshots', ['alert_id'], unique=False)
    op.create_index(op.f('ix_snapshots_camera_id'), 'snapshots', ['camera_id'], unique=False)
    op.create_index(op.f('ix_snapshots_captured_at'), 'snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_snapshots_event_id'), 'snapshots', ['event_id'], unique=False)
    op.create_index(op.f('ix_snapshots_id'), 'snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_snapshots_snapshot_type'), 'snapshots', ['snapshot_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_snapshot_type'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_event_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_captured_at'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_camera_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_alert_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_alert_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_events_zone_id'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_queue_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_camera_id'), table_name='events')
    op.drop_index(op.f('ix_events_alert_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_queue_snapshots_status'), table_name='queue_snapshots')
    op.drop_index(op.f('ix_queue_snapshots_queue_id'), table_name='queue_snapshots')
    op.drop_index(op.f('ix_queue_snapshots_id'), table_name='queue_snapshots')
    op.drop_index(op.f('ix_queue_snapshots_captured_at'), table_name='queue_snapshots')
    op.drop_table('queue_snapshots')
    op.drop_index(op.f('ix_alerts_zone_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_queue_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_camera_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_rois_id'), table_name='rois')
    op.drop_index(op.f('ix_rois_camera_id'), table_name='rois')
    op.drop_table('rois')
    op.drop_index(op.f('ix_queues_zone_id'), table_name='queues')
    op.drop_index(op.f('ix_queues_name'), table_name='queues')
    op.drop_index(op.f('ix_queues_id'), table_name='queues')
    op.drop_index(op.f('ix_queues_camera_id'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_face_detection_logs_zone_id'), table_name='face_detection_logs')
    op.drop_index(op.f('ix_face_detection_logs_watchlist_id'), table_name='face_detection_logs')
    op.drop_index(op.f('ix_face_detection_logs_id'), table_name='face_detection_logs')
    op.drop_index(op.f('ix_face_detection_logs_detected_at'), table_name='face_detection_logs')
    op.drop_index(op.f('ix_face_detection_logs_camera_id'), table_name='face_detection_logs')
    op.drop_table('face_detection_logs')
    op.drop_index(op.f('ix_entry_exit_counts_zone_id'), table_name='entry_exit_counts')
    op.drop_index(op.f('ix_entry_exit_counts_recorded_at'), table_name='entry_exit_counts')
    op.drop_index(op.f('ix_entry_exit_counts_id'), table_name='entry_exit_counts')
    op.drop_index(op.f('ix_entry_exit_counts_camera_id'), table_name='entry_exit_counts')
    op.drop_table('entry_exit_counts')
    op.drop_index(op.f('ix_camera_health_recorded_at'), table_name='camera_health')
    op.drop_index(op.f('ix_camera_health_id'), table_name='camera_health')
    op.drop_index(op.f('ix_camera_health_camera_id'), table_name='camera_health')
    op.drop_table('camera_health')
    op.drop_index(op.f('ix_zone_counts_zone_id'), table_name='zone_counts')
    op.drop_index(op.f('ix_zone_counts_recorded_at'), table_name='zone_counts')
    op.drop_index(op.f('ix_zone_counts_id'), table_name='zone_counts')
    op.drop_table('zone_counts')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_cameras_zone_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_status'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_is_active'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_group_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_type'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_name'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_logged_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_category'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_service_statuses_updated_at'), table_name='service_statuses')
    op.drop_index(op.f('ix_service_statuses_status'), table_name='service_statuses')
    op.drop_index(op.f('ix_service_statuses_service_name'), table_name='service_statuses')
    op.drop_index(op.f('ix_service_statuses_id'), table_name='service_statuses')
    op.drop_table('service_statuses')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_criminal_watchlist_name'), table_name='criminal_watchlist')
    op.drop_index(op.f('ix_criminal_watchlist_id'), table_name='criminal_watchlist')
    op.drop_table('criminal_watchlist')
    op.drop_index(op.f('ix_camera_groups_name'), table_name='camera_groups')
    op.drop_index(op.f('ix_camera_groups_id'), table_name='camera_groups')
    op.drop_table('camera_groups')
    op.drop_index(op.f('ix_ai_models_name'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_model_type'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_is_active'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_id'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
